import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    backgroundColor: "#0f172a",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brand: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "900",
  },
  subtitle: {
    color: "#94a3b8",
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
  },
  headerButton: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    backgroundColor: "#1e293b",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  headerButtonText: {
    color: "#e2e8f0",
    fontWeight: "800",
    fontSize: 12,
  },
  content: {
    padding: 16,
    paddingBottom: 110,
  },
  centerContent: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
  },
  loginCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  logoBox: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#0ea5e9",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  loginTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#0f172a",
  },
  loginHint: {
    color: "#64748b",
    fontWeight: "600",
    marginTop: 4,
    marginBottom: 18,
  },
  tabBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingVertical: 10,
  },
  tabContent: {
    paddingHorizontal: 10,
    gap: 8,
  },
  tabItem: {
    minWidth: 86,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
  },
  tabItemActive: {
    backgroundColor: "#0ea5e9",
  },
  tabLabel: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "900",
    marginTop: 3,
  },
  tabLabelActive: {
    color: "#ffffff",
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 16,
  },
  statCard: {
    flexBasis: "47%",
    flexGrow: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  statValue: {
    color: "#0f172a",
    fontSize: 24,
    fontWeight: "900",
  },
  statLabel: {
    color: "#64748b",
    fontSize: 11,
    fontWeight: "800",
  },
  section: {
    gap: 12,
  },
  sectionTitleWrap: {
    marginBottom: 4,
  },
  sectionTitle: {
    color: "#0f172a",
    fontSize: 22,
    fontWeight: "900",
  },
  sectionSubtitle: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 2,
  },
  sectionSmallTitle: {
    color: "#0f172a",
    fontSize: 14,
    fontWeight: "900",
    marginTop: 14,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 8,
  },
  cardHeader: {
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  cardTitle: {
    color: "#0f172a",
    fontSize: 15,
    fontWeight: "900",
  },
  mutedText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "600",
  },
  detailText: {
    color: "#334155",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "600",
  },
  priceText: {
    color: "#0284c7",
    fontSize: 15,
    fontWeight: "900",
  },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "#e0f2fe",
    color: "#0369a1",
    overflow: "hidden",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 5,
    fontSize: 10,
    fontWeight: "900",
  },
  cardActions: {
    gap: 8,
    marginTop: 4,
  },
  auditItem: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  auditAction: {
    color: "#0f172a",
    fontSize: 13,
    fontWeight: "900",
  },
  formCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 12,
  },
  fieldWrap: {
    gap: 6,
  },
  fieldLabel: {
    color: "#64748b",
    fontSize: 10,
    fontWeight: "900",
    textTransform: "uppercase",
  },
  input: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: "#0f172a",
    fontWeight: "700",
    backgroundColor: "#ffffff",
  },
  textArea: {
    minHeight: 86,
    textAlignVertical: "top",
  },
  primaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#0ea5e9",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  primaryButtonText: {
    color: "#ffffff",
    fontWeight: "900",
    fontSize: 13,
  },
  disabledButton: {
    opacity: 0.6,
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: "#bae6fd",
    backgroundColor: "#f0f9ff",
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  secondaryButtonText: {
    color: "#0369a1",
    fontWeight: "900",
    fontSize: 12,
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.78)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#ffffff",
    maxHeight: "86%",
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    overflow: "hidden",
  },
  modalHeader: {
    backgroundColor: "#0f172a",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    flex: 1,
    paddingRight: 10,
  },
  modalBody: {
    padding: 16,
    gap: 10,
  },
});

export default styles;
